### ISSUE TITLE
Is there any reference paper about the different boundary?

### ISSUE THREAD

**Issue by xichaoqiang** [nmbader/pydisperse#1]
Dear Dr. Bader

Thanks for sharing this great package. I am interested in dispersion curve computation.

Is there any reference paper about the different boundary?

Best regards,
Xi

**Comment by nmbader** [comment]
Hi Xi,
Thank you for your interest.
I have just added 2 pdf files as a documentation with the references included. I hope that helps.
Best,
Milad
